### PR TITLE
.NET Standard 2 support

### PR DESCRIPTION
**Pull request by andrepf**
New solution and projects to build the library for .NET Standard 2.

It supports both protocols: IEC-101 and IEC-104. The support of IEC-101 depends on the [System.IO.Ports](https://www.nuget.org/packages/System.IO.Ports/4.5.0) package and currently only works on Windows. The next release of this package (4.6.0) will add support for Linux/macOS.

### CODE REVIEW

**Comment by mzillgith** [comment]
First, Thanks for the project files.
I wonder why the examples projects are targeted to .NET core 2.2. Wouldn't be sufficient "netcoreapp2.0"? While the test project is targeted to "net462"? So in order to load the solutions without errors it it required to have core 2.2 and framework 4.6.2 installed.

**Comment by andrepf** [comment]
Yes, the projects can be targeted to .NET Core 2.0. I use the version 2.2 because it is the current recomendation, but if you prefer I can change them to target 2.0 (unsupported because of EOL) or 2.1 (current LTS version). Regarding the test project, it can use the same target version as the sample projects.

**Comment by mzillgith** [comment]
Yes that would be good. If the target is .NET core 2.0 it will work for more people.

**Comment by mzillgith** [comment]
Great! Thanks

**Pull request merged**
